CREATE TABLE IF NOT EXISTS buttons (
 id BIGSERIAL PRIMARY KEY, label VARCHAR(120) NOT NULL, href TEXT NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGSERIAL PRIMARY KEY, actor_type VARCHAR(30) NOT NULL, actor_id VARCHAR(255),
 action VARCHAR(100) NOT NULL, entity_type VARCHAR(50), entity_id VARCHAR(255),
 metadata JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
